captainVersion: 4
version: '3.8'
services:
    # GameVault
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: phalcode/gamevault-backend:$$cap_gamevault_version
        restart: always
        environment:
            DB_HOST: srv-captain--$$cap_appname-db
            DB_USERNAME: 'gamevault'
            DB_PASSWORD: $$cap_gamevault_database_password
            METADATA_IGDB_CLIENT_ID: $$cap_igdb_client_id
            METADATA_IGDB_CLIENT_SECRET: $$cap_igdb_client_secret
        volumes:
            - $$cap_appname-files:/files
            - $$cap_appname-media:/media
        caproverExtra:
            containerHttpPort: '8080'
    # Postgres
    $$cap_appname-db:
        image: postgres:$$cap_postgres_version
        restart: always
        environment:
            POSTGRES_USER: gamevault
            POSTGRES_PASSWORD: $$cap_gamevault_database_password
            POSTGRES_DB: gamevault
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_gamevault_version
          label: GameVault Server Version Tag
          defaultValue: 'latest'
          description: Check out the Docker page for the valid tags https://hub.docker.com/r/phalcode/gamevault-backend/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_gamevault_database_password
          label: Database Password
          defaultValue: $$cap_gen_random_hex(14)
          description: 'Your super secret password for your GameVault Database'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_version
          label: Postgres Database Version Tag
          defaultValue: '15-alpine'
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_igdb_client_id
          label: IGDB Client-ID
          defaultValue: ''
          description: 'This is your IGDB Client-ID for retrieving metadata. You can leave it empty for now, but it is recommended to obtain one. More Info: https://gamevau.lt/docs/server-docs/metadata-enrichment/provider-igdb#setup'
          validRegex: /^(?:[a-z0-9]{32})?$/
        - id: $$cap_igdb_client_secret
          label: IGDB Client-Secret
          defaultValue: ''
          description: 'This is your IGDB Client-Secret for retrieving metadata. You can leave it empty for now, but it is recommended to obtain one. More Info: https://gamevau.lt/docs/server-docs/metadata-enrichment/provider-igdb#setup'
          validRegex: /^(?:[a-z0-9]{32})?$/
    instructions:
        start: >-
            GameVault is a source-available self-hosted alternative to traditional Game Platforms. It allows you and your friends to play and track games that are on a fileserver.
            It is recommended to have a read on this setup documentation here before you start: https://gamevau.lt/docs/server-docs/setup
        end: >-
            Done! 🥳
            Your GameVault server should be available at http://$$cap_appname.$$cap_root_domain now.
            Visit https://gamevau.lt/docs/server-docs/setup#what-next to learn how to use it.
    displayName: GameVault
    isOfficial: true
    description: GameVault is a source-available self-hosted alternative to traditional Game Platforms. It allows you and your friends to play and track games that are on a fileserver.
    documentation: More infos & documentation available on https://gamevau.lt
